version: "2"
run:
  tests: false
linters:
  enable:
    - bodyclose
    - errcheck
    - exhaustive
    - goconst
    - godot
    - gomoddirectives
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - prealloc
    - rowserrcheck
    - staticcheck
    - sqlclosecheck
    - tparallel
    - unconvert
    - whitespace
  disable:
    - govet
    - revive
    - unparam
    - wrapcheck
  exclusions:
    rules:
      - text: '(slog|log)\.\w+'
        linters:
          - noctx
    generated: lax
    presets:
      - common-false-positives
    paths:
      - '.*_test\.go'
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    staticcheck:
      checks:
        - "all"
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
    - goimports
  exclusions:
    generated: lax